name: gym_energy
description: "A new Flutter project."

# Prevent the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.1.0
  intl: ^0.19.0
  provider: ^6.1.2
  fl_chart: ^0.69.0
  another_flushbar: ^1.12.30
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
  fake_cloud_firestore: 3.0.3
  flutter_lints: ^3.0.0

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/icons/desktop_icon.ico"  # Ensure the path is correct
    icon_size: 256  # Recommended maximum size for Windows icons


# Flutter settings
flutter:
  uses-material-design: true

  # Add assets to your application
  assets:
    - assets/fonts/Cairo-Regular.ttf
    - assets/fonts/Cairo-Bold.ttf # Include the bold font if you are using it

  # Custom fonts configuration
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
