// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-L1kS1UcONct-XSX7DWMxS55QQmUm3d0',
    appId: '1:774919900411:web:e86ba995d0e73757d8345e',
    messagingSenderId: '774919900411',
    projectId: 'gymenergy-ba2a2',
    authDomain: 'gymenergy-ba2a2.firebaseapp.com',
    storageBucket: 'gymenergy-ba2a2.appspot.com',
    measurementId: 'G-FBB72RZNPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSvJyXe1DdyPGSTnrtNlpT_sX_h093Nj4',
    appId: '1:545848918902:android:39438377a3a8ad33563057',
    messagingSenderId: '545848918902',
    projectId: 'gymenergy-d7b97',
    storageBucket: 'gymenergy-d7b97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0x4QZZ3QlAv6KM1gkd2FNp19ulC_z5Bc',
    appId: '1:545848918902:ios:b47b2e79edb63adb563057',
    messagingSenderId: '545848918902',
    projectId: 'gymenergy-d7b97',
    storageBucket: 'gymenergy-d7b97.appspot.com',
    iosBundleId: 'com.example.gymEnergy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-L1kS1UcONct-XSX7DWMxS55QQmUm3d0',
    appId: '1:774919900411:web:63d89cbe4cc680b8d8345e',
    messagingSenderId: '774919900411',
    projectId: 'gymenergy-ba2a2',
    authDomain: 'gymenergy-ba2a2.firebaseapp.com',
    storageBucket: 'gymenergy-ba2a2.appspot.com',
    measurementId: 'G-SPZMDGDBQ1',
  );

}